name: Rust

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Build-macOS
      run: sh make_macOS.sh
    - name: Build-iOS
      run: sh make_iOS.sh
    - name: Build-Android
      run: ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk-bundle && sh make_android.sh

