name: Rust

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Build-macOS
      run: sh make_macOS.sh
    - name: Build-iOS
      run: sh make_iOS.sh
    - name: Build-Android
      run: |
        export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        ls $ANDROID_HOME/ndk-bundle/
        ls $ANDROID_HOME/ndk-bundle/build/
        ls $ANDROID_HOME/ndk-bundle/build/tools/
        sh make_android.sh
    - name: Show-Result
      run: ls -la Plugins/*
    - name: Commit-Plugins
      run: |
        git config --local user.email "55793780+BigOyayubi@users.noreply.github.com"
        git config --local user.name "BigOyayubi"
        git add -f Plugins/*
        git commit -m "Update Plugins"
    - name: Push Plugins
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}      
