name: Rust

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Build-macOS
      run: sh make_macOS.sh
    - name: Build-iOS
      run: sh make_iOS.sh
    - name: Build-Android
      env: 
        ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle
      run: |
        ls /usr/local/lib/android/sdk/ndk-bundle/
        ls /usr/local/lib/android/sdk/ndk-bundle/build/
        ls /usr/local/lib/android/sdk/ndk-bundle/build/tools/
        sh make_android.sh

